##
## EPITECH PROJECT, 2023
## DEVOPS
## File description:
## integration.yml
##

name: continous-integration

on:
    push:
        branches-ignore: [ga-ignore-*]
    pull_request:
        branches-ignore: [ga-ignore-*]

jobs:

    coding-style:

    compile:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout GH repo
            uses: actions/checkout@v4

          - name: Compile repository
            run: make

          - name: Check binary presence
            run: |
              if [ ! -f ./swapupcase ]; then
                  echo "::error file=swapupcase,
                  title=Binary Error::Binary not found"
                  exit
              fi
              exit 0